version: '3.7'
networks:
  traefik:
    name: traefik
services:
    traefik:
        restart: always
        image: traefik:v2.2
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entryPoints.odoo.address=:80"
            - "--entryPoints.debugpy.address=:5678"
            - "--entryPoints.postgres.address=:5432"
        ports:
            - "80:80"
#            - "127.0.0.1:443:443"
            - "8080:8080"
#            - "8888:8888"
            - "5678:5678"
            - "5432:5432"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - traefik
        labels:
           - "traefik.enable=true"
        hostname: traefik
        container_name: traefik
